/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Cursor = React.memo(function Cursor(props) {
  const { nodes, materials } = useGLTF("/models/cursor.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.rotation.y += 0.003;
  });

  return (
    <group {...props} dispose={null} ref={modelRef}>
      <mesh castShadow receiveShadow geometry={nodes["pointer-cursor"].geometry} material={materials["Material.001"]} position={[-0.131, 0.254, -0.175]} />
    </group>
  );
});

export default Cursor;
useGLTF.preload("/models/cursor.glb");
